default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: routingreact_development
test:
  <<: *default
  database: routingreact_test
production:
  <<: *default
  database: routingreact_production
  username: routingreact
  password: <%= ENV["ROUTINGREACT_DATABASE_PASSWORD"] %>
