default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database:  PruebaIngreso  
  host: localhost
  pool: 5
  username: postgres
  password: 15010204
